server:
  port: 8081

spring:
  profiles:
    active: ${ACTIVE_PROFILE:mongo}
  ---
  # MongoDB Profile (default)
  config:
    activate:
      on-profile: mongo
  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/finanscepte_user}
---
  # JDBC Profile
  config:
    activate:
      on-profile: jdbc
  datasource:
    url: ${JDBC_URL:jdbc:h2:mem:finanscepte_user;DB_CLOSE_DELAY=-1}
    driver-class-name: ${JDBC_DRIVER:org.h2.Driver}
    username: ${JDBC_USERNAME:sa}
    password: ${JDBC_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
      path: /h2-console

security:
  jwt:
    secret: ${JWT_SECRET:fintrack-secret-key-fintrack-secret-key-123}
    expiration-seconds: ${JWT_EXPIRATION_SECONDS:3600}
